//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Domain.Common.Resources.SharedResource", typeof(SharedResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promocode already activated.
        /// </summary>
        public static string ActivatedPromocodeError {
            get {
                return ResourceManager.GetString("ActivatedPromocodeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starter Kit was already issued..
        /// </summary>
        public static string AlreadyIssuedStarterKitError {
            get {
                return ResourceManager.GetString("AlreadyIssuedStarterKitError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are already registered to this marathon..
        /// </summary>
        public static string AlreadyRegisteredError {
            get {
                return ResourceManager.GetString("AlreadyRegisteredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cant delete marathon.
        /// </summary>
        public static string CantDeleteMarathonError {
            get {
                return ResourceManager.GetString("CantDeleteMarathonError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voucher deactivated..
        /// </summary>
        public static string DeactivatedVoucherError {
            get {
                return ResourceManager.GetString("DeactivatedVoucherError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cant delete activated promocode.
        /// </summary>
        public static string DeleteActivatedPromocodeError {
            get {
                return ResourceManager.GetString("DeleteActivatedPromocodeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cant delete voucher with promocodes..
        /// </summary>
        public static string DeleteVoucherWithPromocodesError {
            get {
                return ResourceManager.GetString("DeleteVoucherWithPromocodesError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email already confirmed.
        /// </summary>
        public static string EmailAlreadyConfirmedError {
            get {
                return ResourceManager.GetString("EmailAlreadyConfirmedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to connect email service.
        /// </summary>
        public static string EmailServiceConnectionError {
            get {
                return ResourceManager.GetString("EmailServiceConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email was not confirmed..
        /// </summary>
        public static string EmailWasNotConfirmedError {
            get {
                return ResourceManager.GetString("EmailWasNotConfirmedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Headers in excel file are invalid..
        /// </summary>
        public static string InvalidHeadersInExcelError {
            get {
                return ResourceManager.GetString("InvalidHeadersInExcelError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have entered an invalid promocode.
        /// </summary>
        public static string InvalidPromocodeError {
            get {
                return ResourceManager.GetString("InvalidPromocodeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid sheet name for excel file you uploaded..
        /// </summary>
        public static string InvalidSheetNameError {
            get {
                return ResourceManager.GetString("InvalidSheetNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid token.
        /// </summary>
        public static string InvalidTokenError {
            get {
                return ResourceManager.GetString("InvalidTokenError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no distance age category for your age and gender..
        /// </summary>
        public static string NoDistanceAgeError {
            get {
                return ResourceManager.GetString("NoDistanceAgeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no places to this distance..
        /// </summary>
        public static string NoPlacesError {
            get {
                return ResourceManager.GetString("NoPlacesError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No places for promocodes to distance - {0}.
        /// </summary>
        public static string NoPlacesForPromocodesError {
            get {
                return ResourceManager.GetString("NoPlacesForPromocodesError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} not found.
        /// </summary>
        public static string NotFoundError {
            get {
                return ResourceManager.GetString("NotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your disability has not been confirmed.
        /// </summary>
        public static string NotPWDError {
            get {
                return ResourceManager.GetString("NotPWDError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today&apos;s date is not in the registration range..
        /// </summary>
        public static string OutsideRegistationDateError {
            get {
                return ResourceManager.GetString("OutsideRegistationDateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords do not match.
        /// </summary>
        public static string PasswordsDoNotMatchError {
            get {
                return ResourceManager.GetString("PasswordsDoNotMatchError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment failed.
        /// </summary>
        public static string PaymentDidNotSucceedError {
            get {
                return ResourceManager.GetString("PaymentDidNotSucceedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The payment was not deleted.
        /// </summary>
        public static string PaymentNotDeletedError {
            get {
                return ResourceManager.GetString("PaymentNotDeletedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment was not created.
        /// </summary>
        public static string PaymentNotInitializedError {
            get {
                return ResourceManager.GetString("PaymentNotInitializedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment service does not respond.
        /// </summary>
        public static string PaymentServiceIsNotRespondingError {
            get {
                return ResourceManager.GetString("PaymentServiceIsNotRespondingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The signatures do not match.
        /// </summary>
        public static string SignaturesDoNotMatchError {
            get {
                return ResourceManager.GetString("SignaturesDoNotMatchError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have not confirmed the user agreement and have not filled out the profile.
        /// </summary>
        public static string UserAgreementLicenseAgreementError {
            get {
                return ResourceManager.GetString("UserAgreementLicenseAgreementError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User already exist.
        /// </summary>
        public static string UserAlreadyExistsError {
            get {
                return ResourceManager.GetString("UserAlreadyExistsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User does not exist.
        /// </summary>
        public static string UserDoesNotExistError {
            get {
                return ResourceManager.GetString("UserDoesNotExistError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong password.
        /// </summary>
        public static string WrongPasswordError {
            get {
                return ResourceManager.GetString("WrongPasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong role.
        /// </summary>
        public static string WrongRoleError {
            get {
                return ResourceManager.GetString("WrongRoleError", resourceCulture);
            }
        }
    }
}
