//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    ///   This class was generated by MSBuild using the GenerateResource task.
    ///   To add or remove a member, edit your .resx file then rerun MSBuild.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Build.Tasks.StronglyTypedResourceBuilder", "15.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedResource_ky_kg {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResource_ky_kg() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Domain.Common.Resources.SharedResource.ky-kg", typeof(SharedResource_ky_kg).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Промокод активдештирилген.
        /// </summary>
        public static string ActivatedPromocodeError {
            get {
                return ResourceManager.GetString("ActivatedPromocodeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Башталгыч пакет берилген.
        /// </summary>
        public static string AlreadyIssuedStarterKitError {
            get {
                return ResourceManager.GetString("AlreadyIssuedStarterKitError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сиз бул марафонго катталгансыз..
        /// </summary>
        public static string AlreadyRegisteredError {
            get {
                return ResourceManager.GetString("AlreadyRegisteredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваучер өчүрүлгөн..
        /// </summary>
        public static string DeactivatedVoucherError {
            get {
                return ResourceManager.GetString("DeactivatedVoucherError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Активдештирилген промокодду өчүрүп салуу мүмкүн эмес.
        /// </summary>
        public static string DeleteActivatedPromocodeError {
            get {
                return ResourceManager.GetString("DeleteActivatedPromocodeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Электрондук почта ырасталды.
        /// </summary>
        public static string EmailAlreadyConfirmedError {
            get {
                return ResourceManager.GetString("EmailAlreadyConfirmedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Почта кызматы учурда жооп бербей жатат..
        /// </summary>
        public static string EmailServiceConnectionError {
            get {
                return ResourceManager.GetString("EmailServiceConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Электрондук почта ырастала элек.
        /// </summary>
        public static string EmailWasNotConfirmedError {
            get {
                return ResourceManager.GetString("EmailWasNotConfirmedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel файлындагы аталыштар туура эмес (мүмкүн сиз башка документти жүктөп жатасыз).
        /// </summary>
        public static string InvalidHeadersInExcelError {
            get {
                return ResourceManager.GetString("InvalidHeadersInExcelError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сиз туура эмес промо код киргиздиңиз.
        /// </summary>
        public static string InvalidPromocodeError {
            get {
                return ResourceManager.GetString("InvalidPromocodeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel файлындагы аталыш туура эмес.
        /// </summary>
        public static string InvalidSheetNameException {
            get {
                return ResourceManager.GetString("InvalidSheetNameException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Туура эмес токен.
        /// </summary>
        public static string InvalidTokenError {
            get {
                return ResourceManager.GetString("InvalidTokenError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сиздин жашыңыз жана жынысыңыз боюнча жаш категориясы жок.
        /// </summary>
        public static string NoDistanceAgeError {
            get {
                return ResourceManager.GetString("NoDistanceAgeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Бул аралыкка орун калган жок.
        /// </summary>
        public static string NoPlacesError {
            get {
                return ResourceManager.GetString("NoPlacesError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дистанцияга - {0} жарнамалык коддор үчүн орун калган жок.
        /// </summary>
        public static string NoPlacesForPromocodesError {
            get {
                return ResourceManager.GetString("NoPlacesForPromocodesError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} табылган жок.
        /// </summary>
        public static string NotFoundError {
            get {
                return ResourceManager.GetString("NotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Майыптыгыңыз азырынча ырастала элек.
        /// </summary>
        public static string NotPWDError {
            get {
                return ResourceManager.GetString("NotPWDError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Бүгүнкү күн каттоо дата аралыгына кирбейт.
        /// </summary>
        public static string OutsideRegistationDateError {
            get {
                return ResourceManager.GetString("OutsideRegistationDateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сыр сөздөр дал келбейт.
        /// </summary>
        public static string PasswordsDoNotMatchError {
            get {
                return ResourceManager.GetString("PasswordsDoNotMatchError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сиз колдонуучу келишимин ырастаган жоксуз жана профильди толтурган жоксуз.
        /// </summary>
        public static string UserAgreementLicenseAgreementError {
            get {
                return ResourceManager.GetString("UserAgreementLicenseAgreementError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мындай колдонуучу бар.
        /// </summary>
        public static string UserAlreadyExistsError {
            get {
                return ResourceManager.GetString("UserAlreadyExistsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мындай колдонуучу жок.
        /// </summary>
        public static string UserDoesNotExistError {
            get {
                return ResourceManager.GetString("UserDoesNotExistError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Туура эмес сыр сөз.
        /// </summary>
        public static string WrongPasswordError {
            get {
                return ResourceManager.GetString("WrongPasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Туура эмес роль.
        /// </summary>
        public static string WrongRoleError {
            get {
                return ResourceManager.GetString("WrongRoleError", resourceCulture);
            }
        }
    }
}
