//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    ///   This class was generated by MSBuild using the GenerateResource task.
    ///   To add or remove a member, edit your .resx file then rerun MSBuild.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Build.Tasks.StronglyTypedResourceBuilder", "15.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedResource_ru_ru {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResource_ru_ru() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Domain.Common.Resources.SharedResource.ru-ru", typeof(SharedResource_ru_ru).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Промокод уже активирован.
        /// </summary>
        public static string ActivatedPromocodeError {
            get {
                return ResourceManager.GetString("ActivatedPromocodeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Стартовый пакет уже выдан..
        /// </summary>
        public static string AlreadyIssuedStarterKitError {
            get {
                return ResourceManager.GetString("AlreadyIssuedStarterKitError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы уже зарегистрированы на этот марафон..
        /// </summary>
        public static string AlreadyRegisteredError {
            get {
                return ResourceManager.GetString("AlreadyRegisteredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы не можете удалить марафон.
        /// </summary>
        public static string CantDeleteMarathonError {
            get {
                return ResourceManager.GetString("CantDeleteMarathonError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваучер деактивирован..
        /// </summary>
        public static string DeactivatedVoucherError {
            get {
                return ResourceManager.GetString("DeactivatedVoucherError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невозможно удалить активированный промокод.
        /// </summary>
        public static string DeleteActivatedPromocodeError {
            get {
                return ResourceManager.GetString("DeleteActivatedPromocodeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы не можете удалить ваучер с промокодами.
        /// </summary>
        public static string DeleteVoucherWithPromocodesError {
            get {
                return ResourceManager.GetString("DeleteVoucherWithPromocodesError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Электронная почта уже подтверждена.
        /// </summary>
        public static string EmailAlreadyConfirmedError {
            get {
                return ResourceManager.GetString("EmailAlreadyConfirmedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сервис по отправке почты в данный момент не отвечает.
        /// </summary>
        public static string EmailServiceConnectionError {
            get {
                return ResourceManager.GetString("EmailServiceConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Электронная почта не подтверждена.
        /// </summary>
        public static string EmailWasNotConfirmedError {
            get {
                return ResourceManager.GetString("EmailWasNotConfirmedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заголовки в эксель файле неверные(возможно вы загржуаете не тот документ который скачали).
        /// </summary>
        public static string InvalidHeadersInExcelError {
            get {
                return ResourceManager.GetString("InvalidHeadersInExcelError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы ввели неверный промокод.
        /// </summary>
        public static string InvalidPromocodeError {
            get {
                return ResourceManager.GetString("InvalidPromocodeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неверное название листа в эксель файле..
        /// </summary>
        public static string InvalidSheetNameException {
            get {
                return ResourceManager.GetString("InvalidSheetNameException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неверный токен.
        /// </summary>
        public static string InvalidTokenError {
            get {
                return ResourceManager.GetString("InvalidTokenError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет возрастной категории для вашего возраста и пола..
        /// </summary>
        public static string NoDistanceAgeError {
            get {
                return ResourceManager.GetString("NoDistanceAgeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to На эту дистанцию не осталось мест.
        /// </summary>
        public static string NoPlacesError {
            get {
                return ResourceManager.GetString("NoPlacesError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет мест для промокодов на дистанцию - {0}.
        /// </summary>
        public static string NoPlacesForPromocodesError {
            get {
                return ResourceManager.GetString("NoPlacesForPromocodesError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} не найдено.
        /// </summary>
        public static string NotFoundError {
            get {
                return ResourceManager.GetString("NotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вашу инвалидность еще не подтвердили..
        /// </summary>
        public static string NotPWDError {
            get {
                return ResourceManager.GetString("NotPWDError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сегодняшняя дата не входит в диапазон дат регистрации.
        /// </summary>
        public static string OutsideRegistationDateError {
            get {
                return ResourceManager.GetString("OutsideRegistationDateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароли не совпадают.
        /// </summary>
        public static string PasswordsDoNotMatchError {
            get {
                return ResourceManager.GetString("PasswordsDoNotMatchError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Платеж не прошел.
        /// </summary>
        public static string PaymentDidNotSucceedError {
            get {
                return ResourceManager.GetString("PaymentDidNotSucceedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Платеж не был удален.
        /// </summary>
        public static string PaymentNotDeletedError {
            get {
                return ResourceManager.GetString("PaymentNotDeletedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Платеж не был создан.
        /// </summary>
        public static string PaymentNotInitializedError {
            get {
                return ResourceManager.GetString("PaymentNotInitializedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сервис по оплате не отвечает.
        /// </summary>
        public static string PaymentServiceIsNotRespondingError {
            get {
                return ResourceManager.GetString("PaymentServiceIsNotRespondingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подписи не совпадают.
        /// </summary>
        public static string SignaturesDoNotMatchError {
            get {
                return ResourceManager.GetString("SignaturesDoNotMatchError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы не подтвердили пользовательское соглашение и не заполнили профиль.
        /// </summary>
        public static string UserAgreementLicenseAgreementError {
            get {
                return ResourceManager.GetString("UserAgreementLicenseAgreementError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователь уже существует.
        /// </summary>
        public static string UserAlreadyExistsError {
            get {
                return ResourceManager.GetString("UserAlreadyExistsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователь не существует.
        /// </summary>
        public static string UserDoesNotExistError {
            get {
                return ResourceManager.GetString("UserDoesNotExistError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неверный пароль.
        /// </summary>
        public static string WrongPasswordError {
            get {
                return ResourceManager.GetString("WrongPasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неверная роль.
        /// </summary>
        public static string WrongRoleError {
            get {
                return ResourceManager.GetString("WrongRoleError", resourceCulture);
            }
        }
    }
}
